name: CI / Check
on:
  workflow_call:
jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install --no-install-recommends -y clang-format-15
      - run: CLANG_FORMAT_EXE=clang-format-15 ./scripts/check_format.sh

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install --no-install-recommends -y clang-tidy-15
      - run: cmake -B build -S . -DLANGNES_JSON_BUILD_DOCS=OFF
      - run: CLANG_TIDY_EXE=clang-tidy-15 ./scripts/check_tidy.sh
