name: CI / Docs
on:
  workflow_call:
    inputs:
      cmake-options:
        type: string
        description: CMake options (X=1 Y=2)
        required: false
jobs:
  api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Build documentation
        run: |
          options=()
          if [[ ! -z "${{ inputs.cmake-options }}" ]]; then
            options+=(${{ inputs.cmake-options }})
          fi
          args=()
          for option in "${options[@]}"; do
            args+=("-D${option}")
          done
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Profile "${args[@]}"
          cmake --build build

      - name: Create package
        run: cpack -G "TGZ;ZIP"
        working-directory: build

      - name: Upload distributable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/dist
          retention-days: 1
          if-no-files-found: error
